apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-memory-load
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: load-cpu-dev
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60