apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-cpu-load
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-cpu-dev
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
